services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      APP_USER: ${ORACLE_APP_USER:?defina ORACLE_APP_USER no .env}
      APP_USER_PASSWORD: ${ORACLE_APP_PASSWORD:?defina ORACLE_APP_PASSWORD no .env}
      ORACLE_PASSWORD: ${ORACLE_SYS_PASSWORD:?defina ORACLE_SYS_PASSWORD no .env}
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s
    networks:
      - challenge_net
    restart: unless-stopped
    ports:
      - "1521:1521"

  mongo-db:
    image: mongo:7
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?defina MONGO_USER no .env}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?defina MONGO_PASSWORD no .env}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - challenge_net
    restart: unless-stopped
    ports:
      - "27017:27017"

  petguardian-api:
    build:
      context: .
      dockerfile: PetGuardian.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: enzookuizumi/petguardian-api:v1
    container_name: petguardian-api
    depends_on:
      oracle-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__PetGuardianOracle: "User Id=${ORACLE_APP_USER};Password=${ORACLE_APP_PASSWORD};Data Source=oracle-db:1521/XEPDB1;"
      MongoDb__ConnectionString: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017/?authSource=admin"
      MongoDb__DatabaseName: petguardian_nosql
      Jwt__SecretKey: ${JWT_SECRET_KEY:?defina JWT_SECRET_KEY no .env (mín. 32 caracteres)}
    networks:
      - challenge_net
    restart: on-failure

networks:
  challenge_net:
    driver: bridge

volumes:
  oracle_data:
  mongo_data:
