// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetGuardian.Infrastructure.Persistence;

#nullable disable

namespace PetGuardian.Infrastructure.Migrations
{
    [DbContext(typeof(PetGuardianContext))]
    partial class PetGuardianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGuardian.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_AULA");

                    b.Property<int>("Concluida")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONCLUIDA");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("CONTEUDO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DIFICULDADE");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("MODULO_ID_MODULO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<short>("PontosAula")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("PONTOS_AULA");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("AULA", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_BAIRRO");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CIDADE_ID_CIDADE");

                    b.Property<string>("NomeBairro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_BAIRRO");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("BAIRRO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CIDADE");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ESTADO_ID_ESTADO");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_CIDADE");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("CIDADE", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<Guid>("BairroId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("BAIRRO_ID_BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("RUA");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_ESTADO");

                    b.HasKey("Id");

                    b.ToTable("ESTADO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Historico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_HIST");

                    b.Property<DateTime>("DataHist")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HIST");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PET_ID_PET");

                    b.Property<string>("TipoHist")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_HIST");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("HISTORICO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_MODULO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("TempoConclusao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TEMPO_CONCLUSAO");

                    b.Property<Guid>("TrilhaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TRILHA_ID_TRILHA");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("MODULO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<int>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PORTE");

                    b.Property<Guid>("RacaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("RACA_ID_RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SEXO");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_RACA");

                    b.Property<string>("NomeRaca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_RACA");

                    b.HasKey("Id");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_STATUS");

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("NOME_STATUS");

                    b.HasKey("Id");

                    b.ToTable("STATUS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_TAREFA");

                    b.Property<DateTime?>("Conclusao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONCLUSAO");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PET_ID_PET");

                    b.Property<byte>("PontosTarefa")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PONTOS_TAREFA");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PRAZO");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("STATUS_ID_STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TITULO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_TELEFONE");

                    b.Property<string>("NumDdd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("NUM_DDD");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("NUM_TEL");

                    b.HasKey("Id");

                    b.ToTable("TELEFONE", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PET_ID_PET");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("TRILHA", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("SALT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TELEFONE_ID_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelefoneId")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID_USUARIO");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ENDERECO_ID_ENDERECO");

                    b.HasKey("UsuarioId", "EnderecoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("USUARIO_ENDERECO", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID_USUARIO");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PET_ID_PET");

                    b.Property<int>("ResponPrinc")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("RESPON_PRINC");

                    b.HasKey("UsuarioId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("USUARIO_PET", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Aula", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Enderecos")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Historico", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Historicos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Trilha", "Trilha")
                        .WithMany("Modulos")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Raca", "Raca")
                        .WithMany("Pets")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Tarefas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Status", "Status")
                        .WithMany("Tarefas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Trilhas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Telefone", "Telefone")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Usuario", "TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("UsuariosPet")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PetsVinculados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Tarefas");

                    b.Navigation("Trilhas");

                    b.Navigation("UsuariosPet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("PetsVinculados");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
